//
// Created by liuzikai on 3/25/21.
//

#ifndef META_VISION_SOLAIS_TERMINALPARAMETERS_H
#define META_VISION_SOLAIS_TERMINALPARAMETERS_H

namespace meta {

inline constexpr int TERMINAL_IMAGE_PREVIEW_HEIGHT = 360;

}

#endif //META_VISION_SOLAIS_TERMINALPARAMETERS_H
